name: Stephanie Patterson UX Portfolio
url: "https://StephaniePatterson.github.io"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Stephanie Patterson Personal Website
description: Master's Student in Human-Computer Interaction at Rochester Institute of Technology
author: Stephanie Patterson
logo: /headshot.png
